/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FileSelector: typeof import('./src/components/transfer/FileSelector.vue')['default']
    FileTypeIcon: typeof import('./src/components/transfer/FileTypeIcon.vue')['default']
    ModeSwitcher: typeof import('./src/components/transfer/ModeSwitcher.vue')['default']
    PeerList: typeof import('./src/components/transfer/PeerList.vue')['default']
    ProgressDisplay: typeof import('./src/components/transfer/ProgressDisplay.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
