/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppPicker: typeof import('./src/components/transfer/AppPicker.vue')['default']
    ClipboardImporter: typeof import('./src/components/transfer/ClipboardImporter.vue')['default']
    ContentTypeSelector: typeof import('./src/components/transfer/ContentTypeSelector.vue')['default']
    FileSelector: typeof import('./src/components/transfer/FileSelector.vue')['default']
    FileThumbnail: typeof import('./src/components/transfer/FileThumbnail.vue')['default']
    FileTypeIcon: typeof import('./src/components/transfer/FileTypeIcon.vue')['default']
    FolderPicker: typeof import('./src/components/transfer/FolderPicker.vue')['default']
    LanguageSelector: typeof import('./src/components/settings/LanguageSelector.vue')['default']
    MediaPicker: typeof import('./src/components/transfer/MediaPicker.vue')['default']
    ModeSwitcher: typeof import('./src/components/transfer/ModeSwitcher.vue')['default']
    PeerList: typeof import('./src/components/transfer/PeerList.vue')['default']
    PinConfigDialog: typeof import('./src/components/transfer/PinConfigDialog.vue')['default']
    ProgressDisplay: typeof import('./src/components/transfer/ProgressDisplay.vue')['default']
    ReceiveModeSelector: typeof import('./src/components/transfer/ReceiveModeSelector.vue')['default']
    ReceiveSettingsCard: typeof import('./src/components/transfer/ReceiveSettingsCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectedFileList: typeof import('./src/components/transfer/SelectedFileList.vue')['default']
    SendSettingsCard: typeof import('./src/components/transfer/SendSettingsCard.vue')['default']
    SettingsGroup: typeof import('./src/components/settings/SettingsGroup.vue')['default']
    TextInput: typeof import('./src/components/transfer/TextInput.vue')['default']
    ThemeSelector: typeof import('./src/components/settings/ThemeSelector.vue')['default']
  }
}
